### PR TITLE
Add unit test for duplicate file names

### PR DESCRIPTION
**Pull request by jwest115**
Write `fpp-to-dict` output to txt file and compare against reference (similar to other tools). Added unit test case for duplicate file names.

### CODE REVIEW

**Review by bocchino — COMMENTED** [review]
Looks good, thanks! Why are the empty files dataProducts.ref.txt and multipleTops.ref.txt checked in here? Do we need them?

**Comment by jwest115** [comment]
I don't think we need them, I decided to include them to keep things consistent with other tool unit tests, for example `fpp-to-cpp` https://github.com/nasa/fpp/blob/main/compiler/tools/fpp-to-cpp/test/enum/default.ref.txt.

**Comment by bocchino** [comment]
OK, I agree that makes sense now that we are checking for console output. Thanks!

**Review by bocchino — APPROVED** [review]
Looks good!

**Pull request merged**
